services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./templates:/code/templates
    restart_policy:
        condition: on-failure
        max_attempts: 5  # Change this to your desired constant number
        delay: 5s       # Optional: time to wait between restart attempts
        window: 120s    # Optional: how long to wait before deciding if a restart was successful
