services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8080:80"
    env_file:
      - .env
    volumes:
      - ./app:/code/app
      - ./templates:/code/templates
    restart: always